<?php

namespace Database\Seeders;

use App\Models\Countries;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Countries::insert([
            ['code_s' => 'af', 'code_l' => 'afg', 'name' => 'Afghanistan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ax', 'code_l' => 'ala', 'name' => 'Åland Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'al', 'code_l' => 'alb', 'name' => 'Albania', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'dz', 'code_l' => 'dza', 'name' => 'Algeria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'as', 'code_l' => 'asm', 'name' => 'American Samoa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ad', 'code_l' => 'and', 'name' => 'Andorra', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ao', 'code_l' => 'ago', 'name' => 'Angola', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ai', 'code_l' => 'aia', 'name' => 'Anguilla', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'aq', 'code_l' => 'ata', 'name' => 'Antarctica', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ag', 'code_l' => 'atg', 'name' => 'Antigua and Barbuda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ar', 'code_l' => 'arg', 'name' => 'Argentina', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'am', 'code_l' => 'arm', 'name' => 'Armenia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'aw', 'code_l' => 'abw', 'name' => 'Aruba', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'au', 'code_l' => 'aus', 'name' => 'Australia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'at', 'code_l' => 'aut', 'name' => 'Austria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'az', 'code_l' => 'aze', 'name' => 'Azerbaijan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bs', 'code_l' => 'bhs', 'name' => 'Bahamas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bh', 'code_l' => 'bhr', 'name' => 'Bahrain', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bd', 'code_l' => 'bgd', 'name' => 'Bangladesh', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bb', 'code_l' => 'brb', 'name' => 'Barbados', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'by', 'code_l' => 'blr', 'name' => 'Belarus', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'be', 'code_l' => 'bel', 'name' => 'Belgium', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bz', 'code_l' => 'blz', 'name' => 'Belize', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bj', 'code_l' => 'ben', 'name' => 'Benin', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bm', 'code_l' => 'bmu', 'name' => 'Bermuda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bt', 'code_l' => 'btn', 'name' => 'Bhutan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bo', 'code_l' => 'bol', 'name' => 'Bolivia, Plurinational State of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bq', 'code_l' => 'bes', 'name' => 'Bonaire, Sint Eustatius and Saba', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ba', 'code_l' => 'bih', 'name' => 'Bosnia and Herzegovina', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bw', 'code_l' => 'bwa', 'name' => 'Botswana', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bv', 'code_l' => 'bvt', 'name' => 'Bouvet Island', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'br', 'code_l' => 'bra', 'name' => 'Brazil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'io', 'code_l' => 'iot', 'name' => 'British Indian Ocean Territory', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bn', 'code_l' => 'brn', 'name' => 'Brunei Darussalam', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bg', 'code_l' => 'bgr', 'name' => 'Bulgaria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bf', 'code_l' => 'bfa', 'name' => 'Burkina Faso', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bi', 'code_l' => 'bdi', 'name' => 'Burundi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cv', 'code_l' => 'cpv', 'name' => 'Cabo Verde', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'kh', 'code_l' => 'khm', 'name' => 'Cambodia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cm', 'code_l' => 'cmr', 'name' => 'Cameroon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ca', 'code_l' => 'can', 'name' => 'Canada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ky', 'code_l' => 'cym', 'name' => 'Cayman Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cf', 'code_l' => 'caf', 'name' => 'Central African Republic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'td', 'code_l' => 'tcd', 'name' => 'Chad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cl', 'code_l' => 'chl', 'name' => 'Chile', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cn', 'code_l' => 'chn', 'name' => 'China', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cx', 'code_l' => 'cxr', 'name' => 'Christmas Island', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cc', 'code_l' => 'cck', 'name' => 'Cocos [Keeling] Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'co', 'code_l' => 'col', 'name' => 'Colombia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'km', 'code_l' => 'com', 'name' => 'Comoros', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cg', 'code_l' => 'cog', 'name' => 'Congo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cd', 'code_l' => 'cod', 'name' => 'Congo, Democratic Republic of the', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ck', 'code_l' => 'cok', 'name' => 'Cook Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cr', 'code_l' => 'cri', 'name' => 'Costa Rica', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ci', 'code_l' => 'civ', 'name' => 'Côte d\'Ivoire', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'hr', 'code_l' => 'hrv', 'name' => 'Croatia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cu', 'code_l' => 'cub', 'name' => 'Cuba', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cw', 'code_l' => 'cuw', 'name' => 'Curaçao', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cy', 'code_l' => 'cyp', 'name' => 'Cyprus', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'cz', 'code_l' => 'cze', 'name' => 'Czechia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'dk', 'code_l' => 'dnk', 'name' => 'Denmark', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'dj', 'code_l' => 'dji', 'name' => 'Djibouti', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'dm', 'code_l' => 'dma', 'name' => 'Dominica', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'do', 'code_l' => 'dom', 'name' => 'Dominican Republic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ec', 'code_l' => 'ecu', 'name' => 'Ecuador', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'eg', 'code_l' => 'egy', 'name' => 'Egypt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sv', 'code_l' => 'slv', 'name' => 'El Salvador', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gq', 'code_l' => 'gnq', 'name' => 'Equatorial Guinea', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'er', 'code_l' => 'eri', 'name' => 'Eritrea', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ee', 'code_l' => 'est', 'name' => 'Estonia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sz', 'code_l' => 'swz', 'name' => 'Eswatini', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'et', 'code_l' => 'eth', 'name' => 'Ethiopia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'fk', 'code_l' => 'flk', 'name' => 'Falkland Islands [Malvinas]', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'fo', 'code_l' => 'fro', 'name' => 'Faroe Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'fj', 'code_l' => 'fji', 'name' => 'Fiji', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'fi', 'code_l' => 'fin', 'name' => 'Finland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'fr', 'code_l' => 'fra', 'name' => 'France', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gf', 'code_l' => 'guf', 'name' => 'French Guiana', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pf', 'code_l' => 'pyf', 'name' => 'French Polynesia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tf', 'code_l' => 'atf', 'name' => 'French Southern Territories', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ga', 'code_l' => 'gab', 'name' => 'Gabon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gm', 'code_l' => 'gmb', 'name' => 'Gambia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ge', 'code_l' => 'geo', 'name' => 'Georgia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'de', 'code_l' => 'deu', 'name' => 'Germany', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gh', 'code_l' => 'gha', 'name' => 'Ghana', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gi', 'code_l' => 'gib', 'name' => 'Gibraltar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gr', 'code_l' => 'grc', 'name' => 'Greece', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gl', 'code_l' => 'grl', 'name' => 'Greenland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gd', 'code_l' => 'grd', 'name' => 'Grenada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gp', 'code_l' => 'glp', 'name' => 'Guadeloupe', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gu', 'code_l' => 'gum', 'name' => 'Guam', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gt', 'code_l' => 'gtm', 'name' => 'Guatemala', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gg', 'code_l' => 'ggy', 'name' => 'Guernsey', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gn', 'code_l' => 'gin', 'name' => 'Guinea', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gw', 'code_l' => 'gnb', 'name' => 'Guinea-Bissau', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gy', 'code_l' => 'guy', 'name' => 'Guyana', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ht', 'code_l' => 'hti', 'name' => 'Haiti', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'hm', 'code_l' => 'hmd', 'name' => 'Heard Island and McDonald Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'va', 'code_l' => 'vat', 'name' => 'Holy See', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'hn', 'code_l' => 'hnd', 'name' => 'Honduras', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'hk', 'code_l' => 'hkg', 'name' => 'Hong Kong', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'hu', 'code_l' => 'hun', 'name' => 'Hungary', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'is', 'code_l' => 'isl', 'name' => 'Iceland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'in', 'code_l' => 'ind', 'name' => 'India', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'id', 'code_l' => 'idn', 'name' => 'Indonesia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ir', 'code_l' => 'irn', 'name' => 'Iran, Islamic Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'iq', 'code_l' => 'irq', 'name' => 'Iraq', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ie', 'code_l' => 'irl', 'name' => 'Ireland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'im', 'code_l' => 'imn', 'name' => 'Isle of Man', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'il', 'code_l' => 'isr', 'name' => 'Israel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'it', 'code_l' => 'ita', 'name' => 'Italy', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'jm', 'code_l' => 'jam', 'name' => 'Jamaica', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'jp', 'code_l' => 'jpn', 'name' => 'Japan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'je', 'code_l' => 'jey', 'name' => 'Jersey', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'jo', 'code_l' => 'jor', 'name' => 'Jordan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'kz', 'code_l' => 'kaz', 'name' => 'Kazakhstan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ke', 'code_l' => 'ken', 'name' => 'Kenya', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ki', 'code_l' => 'kir', 'name' => 'Kiribati', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'kp', 'code_l' => 'prk', 'name' => 'Korea, Democratic People\'s Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'kr', 'code_l' => 'kor', 'name' => 'Korea, Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'kw', 'code_l' => 'kwt', 'name' => 'Kuwait', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'kg', 'code_l' => 'kgz', 'name' => 'Kyrgyzstan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'la', 'code_l' => 'lao', 'name' => 'Lao People\'s Democratic Republic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'lv', 'code_l' => 'lva', 'name' => 'Latvia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'lb', 'code_l' => 'lbn', 'name' => 'Lebanon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ls', 'code_l' => 'lso', 'name' => 'Lesotho', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'lr', 'code_l' => 'lbr', 'name' => 'Liberia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ly', 'code_l' => 'lby', 'name' => 'Libya', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'li', 'code_l' => 'lie', 'name' => 'Liechtenstein', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'lt', 'code_l' => 'ltu', 'name' => 'Lithuania', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'lu', 'code_l' => 'lux', 'name' => 'Luxembourg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mo', 'code_l' => 'mac', 'name' => 'Macao', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mg', 'code_l' => 'mdg', 'name' => 'Madagascar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mw', 'code_l' => 'mwi', 'name' => 'Malawi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'my', 'code_l' => 'mys', 'name' => 'Malaysia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mv', 'code_l' => 'mdv', 'name' => 'Maldives', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ml', 'code_l' => 'mli', 'name' => 'Mali', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mt', 'code_l' => 'mlt', 'name' => 'Malta', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mh', 'code_l' => 'mhl', 'name' => 'Marshall Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mq', 'code_l' => 'mtq', 'name' => 'Martinique', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mr', 'code_l' => 'mrt', 'name' => 'Mauritania', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mu', 'code_l' => 'mus', 'name' => 'Mauritius', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'yt', 'code_l' => 'myt', 'name' => 'Mayotte', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mx', 'code_l' => 'mex', 'name' => 'Mexico', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'fm', 'code_l' => 'fsm', 'name' => 'Micronesia, Federated States of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'md', 'code_l' => 'mda', 'name' => 'Moldova, Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mc', 'code_l' => 'mco', 'name' => 'Monaco', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mn', 'code_l' => 'mng', 'name' => 'Mongolia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'me', 'code_l' => 'mne', 'name' => 'Montenegro', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ms', 'code_l' => 'msr', 'name' => 'Montserrat', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ma', 'code_l' => 'mar', 'name' => 'Morocco', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mz', 'code_l' => 'moz', 'name' => 'Mozambique', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mm', 'code_l' => 'mmr', 'name' => 'Myanmar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'na', 'code_l' => 'nam', 'name' => 'Namibia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'nr', 'code_l' => 'nru', 'name' => 'Nauru', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'np', 'code_l' => 'npl', 'name' => 'Nepal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'nl', 'code_l' => 'nld', 'name' => 'Netherlands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'nc', 'code_l' => 'ncl', 'name' => 'New Caledonia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'nz', 'code_l' => 'nzl', 'name' => 'New Zealand', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ni', 'code_l' => 'nic', 'name' => 'Nicaragua', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ne', 'code_l' => 'ner', 'name' => 'Niger', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ng', 'code_l' => 'nga', 'name' => 'Nigeria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'nu', 'code_l' => 'niu', 'name' => 'Niue', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'nf', 'code_l' => 'nfk', 'name' => 'Norfolk Island', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mk', 'code_l' => 'mkd', 'name' => 'North Macedonia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mp', 'code_l' => 'mnp', 'name' => 'Northern Mariana Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'no', 'code_l' => 'nor', 'name' => 'Norway', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'om', 'code_l' => 'omn', 'name' => 'Oman', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pk', 'code_l' => 'pak', 'name' => 'Pakistan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pw', 'code_l' => 'plw', 'name' => 'Palau', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ps', 'code_l' => 'pse', 'name' => 'Palestine, State of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pa', 'code_l' => 'pan', 'name' => 'Panama', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pg', 'code_l' => 'png', 'name' => 'Papua New Guinea', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'py', 'code_l' => 'pry', 'name' => 'Paraguay', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pe', 'code_l' => 'per', 'name' => 'Peru', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ph', 'code_l' => 'phl', 'name' => 'Philippines', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pn', 'code_l' => 'pcn', 'name' => 'Pitcairn', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pl', 'code_l' => 'pol', 'name' => 'Poland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pt', 'code_l' => 'prt', 'name' => 'Portugal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pr', 'code_l' => 'pri', 'name' => 'Puerto Rico', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'qa', 'code_l' => 'qat', 'name' => 'Qatar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 're', 'code_l' => 'reu', 'name' => 'Réunion', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ro', 'code_l' => 'rou', 'name' => 'Romania', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ru', 'code_l' => 'rus', 'name' => 'Russian Federation', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'rw', 'code_l' => 'rwa', 'name' => 'Rwanda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'bl', 'code_l' => 'blm', 'name' => 'Saint Barthélemy', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sh', 'code_l' => 'shn', 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'kn', 'code_l' => 'kna', 'name' => 'Saint Kitts and Nevis', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'lc', 'code_l' => 'lca', 'name' => 'Saint Lucia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'mf', 'code_l' => 'maf', 'name' => 'Saint Martin [French part]', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'pm', 'code_l' => 'spm', 'name' => 'Saint Pierre and Miquelon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'vc', 'code_l' => 'vct', 'name' => 'Saint Vincent and the Grenadines', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ws', 'code_l' => 'wsm', 'name' => 'Samoa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sm', 'code_l' => 'smr', 'name' => 'San Marino', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'st', 'code_l' => 'stp', 'name' => 'Sao Tome and Principe', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sa', 'code_l' => 'sau', 'name' => 'Saudi Arabia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sn', 'code_l' => 'sen', 'name' => 'Senegal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'rs', 'code_l' => 'srb', 'name' => 'Serbia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sc', 'code_l' => 'syc', 'name' => 'Seychelles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sl', 'code_l' => 'sle', 'name' => 'Sierra Leone', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sg', 'code_l' => 'sgp', 'name' => 'Singapore', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sx', 'code_l' => 'sxm', 'name' => 'Sint Maarten [Dutch part]', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sk', 'code_l' => 'svk', 'name' => 'Slovakia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'si', 'code_l' => 'svn', 'name' => 'Slovenia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sb', 'code_l' => 'slb', 'name' => 'Solomon Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'so', 'code_l' => 'som', 'name' => 'Somalia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'za', 'code_l' => 'zaf', 'name' => 'South Africa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gs', 'code_l' => 'sgs', 'name' => 'South Georgia and the South Sandwich Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ss', 'code_l' => 'ssd', 'name' => 'South Sudan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'es', 'code_l' => 'esp', 'name' => 'Spain', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'lk', 'code_l' => 'lka', 'name' => 'Sri Lanka', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sd', 'code_l' => 'sdn', 'name' => 'Sudan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sr', 'code_l' => 'sur', 'name' => 'Suriname', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sj', 'code_l' => 'sjm', 'name' => 'Svalbard and Jan Mayen', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'se', 'code_l' => 'swe', 'name' => 'Sweden', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ch', 'code_l' => 'che', 'name' => 'Switzerland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'sy', 'code_l' => 'syr', 'name' => 'Syrian Arab Republic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tw', 'code_l' => 'twn', 'name' => 'Taiwan, Province of China', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tj', 'code_l' => 'tjk', 'name' => 'Tajikistan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tz', 'code_l' => 'tza', 'name' => 'Tanzania, United Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'th', 'code_l' => 'tha', 'name' => 'Thailand', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tl', 'code_l' => 'tls', 'name' => 'Timor-Leste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tg', 'code_l' => 'tgo', 'name' => 'Togo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tk', 'code_l' => 'tkl', 'name' => 'Tokelau', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'to', 'code_l' => 'ton', 'name' => 'Tonga', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tt', 'code_l' => 'tto', 'name' => 'Trinidad and Tobago', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tn', 'code_l' => 'tun', 'name' => 'Tunisia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tr', 'code_l' => 'tur', 'name' => 'Türkiye', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tm', 'code_l' => 'tkm', 'name' => 'Turkmenistan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tc', 'code_l' => 'tca', 'name' => 'Turks and Caicos Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'tv', 'code_l' => 'tuv', 'name' => 'Tuvalu', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ug', 'code_l' => 'uga', 'name' => 'Uganda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ua', 'code_l' => 'ukr', 'name' => 'Ukraine', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ae', 'code_l' => 'are', 'name' => 'United Arab Emirates', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'gb', 'code_l' => 'gbr', 'name' => 'United Kingdom of Great Britain and Northern Ireland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'us', 'code_l' => 'usa', 'name' => 'United States of America', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'um', 'code_l' => 'umi', 'name' => 'United States Minor Outlying Islands', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'uy', 'code_l' => 'ury', 'name' => 'Uruguay', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'uz', 'code_l' => 'uzb', 'name' => 'Uzbekistan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'vu', 'code_l' => 'vut', 'name' => 'Vanuatu', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 've', 'code_l' => 'ven', 'name' => 'Venezuela, Bolivarian Republic of', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'vn', 'code_l' => 'vnm', 'name' => 'Viet Nam', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'vg', 'code_l' => 'vgb', 'name' => 'Virgin Islands [British]', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'vi', 'code_l' => 'vir', 'name' => 'Virgin Islands [U.S.]', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'wf', 'code_l' => 'wlf', 'name' => 'Wallis and Futuna', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'eh', 'code_l' => 'esh', 'name' => 'Western Sahara', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'ye', 'code_l' => 'yem', 'name' => 'Yemen', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'zm', 'code_l' => 'zmb', 'name' => 'Zambia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code_s' => 'zw', 'code_l' => 'zwe', 'name' => 'Zimbabwe', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
        ]);
    }
}
