<?php

namespace App\Http\Controllers;

use App\Services\AspImportService;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;

class AspImportController extends Controller
{
    public function __construct(private AspImportService $service)
    {
        //$this->middleware(['auth']); // по избор
    }

    /**
     * GET /asp-import?root=/absolute/path
     * Враќа stream download на asp_import.sql
     */
    public function downloadSql(Request $request): StreamedResponse
    {
        //$root = $request->query('root', base_path()); // постави што сметаш default
        $root = $request->input('root', config('asp_import.default_root'));
        $result = $this->service->generateSql($root);

        $filename = 'asp_import.sql';
        $sql = $result['sql'];
        $total = $result['total'];
        $skipped = $result['skipped'];

        // можеш и header коментар:
        $header = "-- Generated by AspImportService\n-- Total INSERTs: {$total}\n-- Skipped folders not in map: {$skipped}\n\n";
        $payload = $header . $sql;

        return response()->streamDownload(function() use ($payload) {
            echo $payload;
        }, $filename, [
            'Content-Type' => 'application/sql; charset=UTF-8',
        ]);
    }

    /**
     * POST /asp-import/preview
     * Враќа JSON (корисно за UI preview)
     */
    public function preview(Request $request)
    {
        //$root = $request->input('root', base_path());
        $root = $request->input('root', config('asp_import.default_root'));
        $result = $this->service->generateSql($root);

        return response()->json([
            'total'   => $result['total'],
            'skipped' => $result['skipped'],
            'first_2k_sql' => mb_substr($result['sql'], 0, 2000),
        ]);
    }
}
